# Generated by Django 3.0.2 on 2020-02-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200220_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
