# Generated by Django 3.0.2 on 2020-02-15 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
