# Generated by Django 3.0.2 on 2020-02-15 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200215_1801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Voter',
        ),
    ]
