# Generated by Django 3.0.2 on 2020-02-21 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200217_2128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
